apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualHubRoutingIntent
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/virtualhubroutingintent
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    routingPolicy:
    - destinations:
      - Internet
      name: InternetTrafficPolicy
      nextHopSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    virtualHubIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.upbound.io/v1beta2
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/virtualhubroutingintent
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: AZFW_Hub
    skuTier: Standard
    virtualHub:
    - publicIpCount: 1
      virtualHubId: ${azurerm_virtual_hub.example.id}

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/virtualhubroutingintent
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualHub
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/virtualhubroutingintent
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressPrefix: 10.0.1.0/24
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    virtualWanIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualWAN
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/virtualhubroutingintent
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
